### ISSUE TITLE
instagram not working

### ISSUE THREAD

**Issue by robindz** [qsniyg/maxurl#1042]
Triggering the script on https://www.instagram.com/p/CaF9spEh3FF/ causes the following error to be shown in the console.

```
TypeError: Cannot read properties of null (reading '1')
    at get_sharedData_from_resptext (userscript.user.js:18968:34)
    at fill_graphql_cache_with_postpage (userscript.user.js:19760:21)
    at request_post (userscript.user.js:19988:5)
    at parse_single_el_info (userscript.user.js:20034:14)
    at parse_el_info (userscript.user.js:20053:14)
    at common_functions.instagram_parse_el_info (userscript.user.js:20059:10)
    at userscript.user.js:49214:55
    at bigimage (userscript.user.js:49215:6)
    at do_bigimage (userscript.user.js:92569:12)
    at bigimage_recursive (userscript.user.js:92659:9)
```

**Comment by qsniyg** [comment]
Yeah, unfortunately IG removed `_sharedData`, so I need to update the code accordingly.

For simplicity, I'll close this in favor of https://github.com/qsniyg/maxurl/issues/1023, as it appears to be the same issue (logs from other users around the time #1023 was opened matched the log you sent).

**Comment by qsniyg** [comment]
@robindz Unless you're using a browser with an older JS execution engine, IG should now work properly.

**Comment by robindz** [comment]
@qsniyg  Late reply, sorry. lg2m!
