### ISSUE TITLE
"Loading" cursor does not disappear after the image is loaded

### ISSUE THREAD

**Issue by oifj34f34f** [qsniyg/maxurl#1238]
OS: Linux
Browser: Any

![](https://github.com/qsniyg/maxurl/assets/128177553/8cced906-f605-4889-a0e2-e6053eb07b08)

**Comment by qsniyg** [comment]
Is this specific to one website? If so, could you send a link to the site?

**Comment by oifj34f34f** [comment]
This happens on every site when using the extension (userscript works fine) in both Firefox and Chromium

**Comment by oifj34f34f** [comment]
I just freshly installed Google Chrome on Arch Linux and Image Max URL via Developer Mode (.crx) and the problem was there. I'm using Sway window manager.

**Comment by qsniyg** [comment]
@oifj34f34f Strange. Are there any errors in the browser console?

I assume that the loading cursor stays when the mouse cursor moves too?

**Comment by oifj34f34f** [comment]
I get four errors in console:
```
https://github.com/qsniyg/maxurl/assets/128177553/d5a945ed-94e2-4f82-b765-d1cb370ff057

**Comment by oifj34f34f** [comment]
I get four errors in console:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-M6Ysz0+Rk4NS0oJRgQlAcfTBnQYhP6Zx0KLoS2OqDb8='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

238546.png:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-kZIsqHPSISIo2t1pH7cXKP7WqETBpurMjGw/57SZwqg='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

238546.png:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-zMSqd3IdI0P85bMS1pHPulcrWrNFUbioxKEvO08Bg9I='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

238546.png:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'type')
    at is_probably_audio (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:63466:22)
    at chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:61347:37
    at newoptions.cb (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:60649:6)
    at do_end (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:60462:6)
    at options.cb (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:60466:6)
    at bigimage_recursive (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:60489:12)
    at bigimage_recursive_loop (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:60691:10)
    at do_redirect_sub (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:61320:3)
    at do_redirect (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:61400:3)
    at start (chrome-extension://momhpkepmajdopjgahiglmboldkepibg/userscript.user.js:73171:6)
```

Demonstration:


https://github.com/qsniyg/maxurl/assets/128177553/f7cdd4d3-b1cc-473c-8f09-d5679e72971d

**Comment by qsniyg** [comment]
@oifj34f34f Thanks, the issue should actually be fixed in the the latest git (https://github.com/qsniyg/maxurl/commit/3ea0607658aa12f7694022f3de3a88231febff48#diff-4f927243adee8a4cda903a7d07f867257509ea44db12d8892193e589b61bf1d9R112650). Please try and let me know.

**Comment by oifj34f34f** [comment]
Just tried it, now the bug is gone. Thanks!
